sonar.organization=joegoico
sonar.projectKey=joegoico_Le-Groupe-Gym
sonar.projectName=Le-Groupe-Gym
sonar.projectVersion=1.0.0

# Archivos de código
sonar.sources=lib
sonar.tests=test
sonar.language=dart
sonar.sourceEncoding=UTF-8

# Ignorar código generado automáticamente por Flutter (freezed, g.dart, etc.)
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, lib/generated/**

# Cobertura de tests
sonar.dart.lcov.reportPath=coverage/lcov.info
